Ha updates
SamEdwardes/rstudio-team-pulumi-recipes pull request #1
Opened 2022-05-26 02:17 UTC by kmasiello

Made two changes:
- removed `www-host-name` from /etc/rstudio/load-balancer because this is not needed
- added two variables at the top of __main__.py to input the user's name and email to propagate through the assets deployed to AWS.

2022-05-26 02:20 UTC, kmasiello commented
I also want to add the efs mounts to the /etc/fstab file to ensure it remounts if the EC2 reboots.  I am just not confident yet that I've found the right syntax.  I *believe* that adding this to the justfile will do it: 
```
    #!/bin/bash
    sudo bash -c 'cat <<EOF > /etc/rstudio/fstab
    # mount efs
    "${{EFS_ID}}.efs.us-east-2.amazonaws.com:/ $ SSH/mnt/efs nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0"
```
but I don't want to tear down my existing infrastructure quite yet to be able to test it.  If you've got a chance to test on your end, let's go for it! :)

2022-05-26 20:27 UTC, SamEdwardes requested changes

2022-05-26 20:27 UTC, SamEdwardes commented on recipes/rsw-ha/templates/justfile
> +    EOF'
I am getting an error on this command. With justfile I don't think you can have a *shebang* in the middle of a "script". This part:

```
    #!/bin/bash
    sudo bash -c 'cat <<EOF > /etc/fstab
    # mount efs
    {{EFS_ID}}:/ /etc/fstab efs defaults,_netdev 0 0


    EOF'
```

Should be its own just command.

2022-05-26 20:33 UTC, SamEdwardes commented
Hey Katie - thank you for making the updates. I was inspired by your approach of adding the two variables at the top. I started playing around with it and thought it may be more in the fashion of pulumi to use the `pulumi config` command pass in the information that way instead of hard coding it into the code. So I made a few updates:

- Updated __main__.py to use pulumi config to pull in config options. This replaces harding coding values and using `os.getenv`.
- Added instructions to the README on how to set up the config.

2022-05-26 21:00 UTC, SamEdwardes commented on recipes/rsw-ha/templates/justfile
> +    EOF'
Fixed in caec0fd

2022-05-26 21:01 UTC, SamEdwardes approved these changes

2022-06-03 20:36 UTC, kmasiello commented
@SamEdwardes pushed a few more commits to clean things up and fixed some dramatic errors with the /etc/fstab addition. 
In another PR it would be great to implement local launcher.

2022-06-14 21:30 UTC, SamEdwardes commented
Sorry, this got pushed to the backlog. Merging at last!

2022-06-14 21:30 UTC, merged